version: "3"

services:
 backend:
  image: ileriarowolo/djangoapp
  restart: always
  command: ["python", "manage.py", "runserver"]
  ports:
   - "8000:8000"

 frontend:
  image: ileriarowolo/reactapp
  restart: always
  command: ["npm", "start"]
  ports:
   - "3000:3000"

